[program:sshd]
command=/usr/sbin/sshd -D
autorestart=true

[program:cron]
command=/usr/sbin/cron -f
autorestart=true

[program:smbd]
command=/usr/sbin/smbd --foreground --no-process-group
autorestart=true

[program:nmbd]
command=/usr/sbin/nmbd --foreground --no-process-group
autorestart=true

[program:redis]
command=/usr/bin/redis-server /etc/redis/redis.conf
autorestart=true

[program:cairn-admin]
command=python3 /opt/admin/admin_panel.py
autorestart=true
