[program:sshd]
command=/usr/sbin/sshd -D
autorestart=true

[program:cron]
command=/usr/sbin/cron -f
autorestart=true

[program:php-fpm]
command=/bin/bash -c "exec $(ls /usr/sbin/php-fpm* | head -n1) -F"
autorestart=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autorestart=true

[program:webmail]
command=python3 /opt/webmail/webmail.py
autorestart=true
